# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jc21/nginx-proxy-manager
  pullPolicy: IfNotPresent
  tag: 2.14.0@sha256:2aa69b382a384b676c0d4f1d6f2eac40ecd478fcf7af1cfb3f9f1d3cd0c81e12
service:
  main:
    ports:
      main:
        targetPort: 81
        protocol: http
        port: 10582
  web:
    enabled: true
    ports:
      web:
        enabled: true
        targetPort: 80
        protocol: http
        port: 10583
  websecure:
    enabled: true
    ports:
      websecure:
        enabled: true
        targetPort: 443
        protocol: https
        port: 10584
persistence:
  data:
    enabled: true
    mountPath: /data
    size: 256Gi
  letsencrypt:
    enabled: true
    mountPath: /etc/letsencrypt
    size: 256Gi
mariadb:
  enabled: true
  mariadbUsername: npm
  mariadbDatabase: npm

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/check-health
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/check-health
            startup:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/check-health
          env:
            DISABLE_IPV6: true
            DB_MYSQL_PORT: 3306
            DB_MYSQL_NAME: "{{ .Values.mariadb.mariadbDatabase }}"
            DB_MYSQL_USER: "{{ .Values.mariadb.mariadbUsername }}"
            DB_MYSQL_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_MYSQL_PASSWORD: "{{ .Values.mariadb.password }}"
