# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/wizarrrr/wizarr
  pullPolicy: IfNotPresent
  tag: v2026.2.0@sha256:6b5cfda2b56b902f915eef6bdf03880ef0f4f8f6cda4f264426db2bac93b2655
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5690
        port: 10596
securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            DISABLE_BUILTIN_AUTH: false
persistence:
  database:
    enabled: true
    mountPath: /data/database
  varrun:
    enabled: false
    type: emptyDir
    mountPath: /var/run
  nginxrun:
    enabled: true
    type: emptyDir
    mountPath: /run/nginx
