# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/brotandgames/ciao
  tag: latest@sha256:90a9cc0166e77091dc147e11a54d87672c3472f66d052a6075d0008fa8534853
persistence:
  databaselocation:
    enabled: true
    mountPath: /app/db/sqlite

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8090
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_KEY_BASE: sensitive_secret_key_base
            SMTP_ADDRESS: smtp.yourhost.com
            SMTP_AUTHENTICATION: plain
            SMTP_DOMAIN: smtp.yourhost.com
            SMTP_EMAIL_FROM: ciao@yourhost.com
            SMTP_EMAIL_TO: you@yourhost.com
            SMTP_ENABLE_STARTTLS_AUTO: "true"
            SMTP_PASSWORD: sensitive_password
            SMTP_PORT: "587"
            SMTP_USERNAME: ciao
