# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jenkins/jenkins
  pullPolicy: IfNotPresent
  tag: 2.544-jdk17@sha256:c9059deaa1a6b393ea6a447b13efca888d1817a57b924df9424a7075f51d9348
security:
  container:
    runAsGroup: 1000
    runAsUser: 1000
  pod:
    fsGroup: 1000
# securityContext:
#   readOnlyRootFilesystem: false
jenkins:
  java_opts: []
  jenkins_opts: []
  jenkins_java_opts: []
  plugins_force_upgrade: false
  upgrade_if_no_marker: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /login
            readiness:
              type: http
              path: /login
            startup:
              type: tcp
          envFrom:
            - secretRef:
                name: "jenkins-secret"
service:
  main:
    ports:
      main:
        protocol: http
        port: 10280
  agent:
    enabled: true
    ports:
      agent:
        enabled: true
        port: 50000
persistence:
  data:
    enabled: true
    mountPath: /var/jenkins_home
