# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cglatot/pasta
  pullPolicy: IfNotPresent
  tag: 2.2.6@sha256:b8f601d17e3eebb443d0e87b87cf4503be8235f9149b4958a46965679c8dcc93
service:
  main:
    ports:
      main:
        port: 10302
        protocol: http
        targetPort: 80

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
