# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/vstavrinov/acestream-service
  tag: 2.1.1.1@sha256:b7d90643e3f6529e53210161ba3674814f8b761da679f5840bea90957d5da674
persistence:
  acestreamcache:
    enabled: true
    mountPath: /srv/acestream/.ACEStream

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8008
        protocol: tcp
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ENTRY: "{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.main.ports.main.port }}"
            SCHEME: http
