# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/octoprint/octoprint
  tag: 1.11.7@sha256:49bea4ebfd0cefa9289f058574e7eda6d2de201f1b74309e0c10019e5ec58f04
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10021
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: "/octoprint"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ENABLE_MJPG_STREAMER: "true"
            # -- sets the Mjpg stream imput parameters
            # Example "-y -n -r 640x480"
            MJPG_STREAMER_INPUT:
            # -- sets the camera dev parameters
            # Example "/dev/video0"
            CAMERA_DEV:
