# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/shokoanime/server
  pullPolicy: IfNotPresent
  tag: v5.3.1@sha256:8bfa235fc36a7147443679c242368f30a532e12de3f52e0de2dcc7743fa37044
service:
  main:
    ports:
      main:
        port: 8111
        protocol: http
        targetPort: 8111
persistence:
  appdata:
    enabled: true
    mountPath: /home/shoko/.shoko/

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
