# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/anotherstranger/borg-server
  pullPolicy: IfNotPresent
  tag: 2.8.3@sha256:2ab4d6e959649133be0c71ec8d265f0bb38751381036c515d47256e44668a6f2

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: tcp
        targetPort: 22
        port: 8022

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BORG_UID: "{{ .Values.securityContext.container.PUID }}"
            BORG_GID: "{{ .Values.securityContext.pod.fsGroup }}"
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL

persistence:
  borg:
    enabled: true
    mountPath: "/var/lib/docker-borg"
  backups:
    enabled: true
    mountPath: "/home/borg/backups"
  ssh:
    enabled: true
    mountPath: "/home/borg/.ssh"
