# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/ronivay/xen-orchestra
  tag: 5.196.3@sha256:1ce34542a528b460281c3c3010c886f800c8c3b0ec864d29ac9e03875ef63c8b
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: https
        port: 10324
persistence:
  xo-data:
    enabled: true
    mountPath: "/var/lib/xo-server"
  redis-data:
    enabled: true
    mountPath: "/var/lib/redis"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      add:
        - SYS_ADMIN
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - /healthcheck.sh
            readiness:
              enabled: true
              type: exec
              command:
                - /healthcheck.sh
            startup:
              enabled: true
              type: exec
              command:
                - /healthcheck.sh
          env:
            HTTPS_PORT: "{{ .Values.service.main.ports.main.port }}"
            # Just so it doesn't try to bind port 80
            HTTP_PORT: "{{ add1 .Values.service.main.ports.main.port }}"
            REDIRECT_TO_HTTPS: true
