# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/it-tools
  pullPolicy: IfNotPresent
  tag: 2024.10.22@sha256:61cc5799a8990817710aca96bee4aa958640a1f58048edfd6e9241a735d58a78
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
