# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/deluan/navidrome
  pullPolicy: IfNotPresent
  tag: 0.60.3@sha256:a5dce8f33304714dd138e870cca0dcab3d937ca236be1a9f2b97da009d1a0048
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_MUSICFOLDER: /music
            ND_SCANNER_SCHEDULE: "@every 15m"
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
            ND_ENABLETRANSCODINGCONFIG: false
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
