# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/nicolargo/glances
  pullPolicy: IfNotPresent
  tag: ubuntu-4.5.0.5-full@sha256:8f58bc72704250bd8c4b8fc9bd138c1440782cf2226afcac8a95b52ebc4fe4ed
workload:
  main:
    podSpec:
      # Needed for Running Tasks
      # hostPID: true
      # Needed for Host Network Stats
      # hostNetwork: true
      containers:
        main:
          env:
            GLANCES_OPT: "-w -p {{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 61208
securityContext:
  container:
    PUID: 1000
    runAsGroup: 1000
    runAsUser: 1000
