# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ubooquity
  pullPolicy: IfNotPresent
  tag: 3.1.0@sha256:1e8d0faa39b0f9999c8fe3e4d317ec36dd5cb54530394de814436a948a5139a0
service:
  main:
    ports:
      main:
        targetPort: 2202
        port: 2202
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        targetPort: 2203
        port: 2203
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  books:
    enabled: true
    mountPath: "/books"
  comics:
    enabled: true
    mountPath: "/comics"
  files:
    enabled: true
    mountPath: "/files"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            MAXMEM: 512
