# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shaneisrael/fireshare
  tag: 1.4.2@sha256:a5cef8ae69ab11590d529b3f3d8d40eab3915002652f71937763033b837a1e00

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_KEY:
              secretKeyRef:
                name: fireshare-secrets
                key: SECRET_KEY
            MINUTES_BETWEEN_VIDEO_SCANS: 5
            ADMIN_PASSWORD: "changeme"
            # TODO ADD LDAP
            # LDAP_ENABLE: false
            # LDAP_URL: ""
            # LDAP_BINDDN: ""
            # LDAP_PASSWORD: ""
            # LDAP_BASEDN: ""
            # LDAP_USER_FILTER: ""
            # LDAP_ADMIN_GROUP: ""

service:
  main:
    ports:
      main:
        port: 10287
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data
  processeddata:
    enabled: true
    mountPath: /processed
  videos:
    enabled: true
    mountPath: /videos
