# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/onlyoffice/documentserver
  tag: 9.3.0@sha256:4cb83b05d91d6776de74a9f65645aac8838161b27a95ae00c776f58ae53dd111
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10043
        targetPort: 80
# Enabled postgres
cnpg:
  main:
    enabled: true
    user: onlyoffice
    database: onlyoffice
# Enabled redis
redis:
  enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/healthcheck"
            readiness:
              path: "/healthcheck"
            startup:
              path: "/healthcheck"
          env:
            WOPI_ENABLED: true
            JWT_ENABLED: true
            DB_TYPE: "postgres"
            DB_PORT: 5432
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            REDIS_SERVER_PORT: 6379
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            DB_PWD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            REDIS_SERVER_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_SERVER_PASS:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: redis-password
            JWT_SECRET: "randomgeneratedstring"
