# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: 1.5.2@sha256:3a9bcbc609ba6bd42fe3699c2441765d2393143087e814361c5ce5614863419f

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/api/v2/heartbeat"
            readiness:
              path: "/api/v2/heartbeat"
            startup:
              path: "/api/v2/heartbeat"
          env:
            IS_PERSISTENT: true

persistence:
  config:
    enabled: true
    mountPath: "/chroma/chroma"
